import { createUnitContent, type UnitContentSeed } from "./factories";

const stage1Seeds = [
  {
    stage: 1,
    unitId: "S1-U1",
    order: 1,
    titleJa: "be動詞で状態を表す",
    descriptionJa: "am・is・areの肯定文、否定文、疑問文を整理します。",
    objectivesJa: [
      "主語に合わせてam・is・areを選べる",
      "be動詞の否定文と疑問文を作れる",
    ],
    explanationJa:
      "be動詞は、人や物の名前・状態・場所を結び付けます。Iにはam、一人や一つにはis、youや複数にはareを使います。",
    examples: [
      { en: "She is busy.", ja: "彼女は忙しいです。" },
      { en: "They are not at home.", ja: "彼らは家にいません。" },
    ],
    recallJa: "I、she、theyのそれぞれに合うbe動詞を、答えを見ずに言ってみましょう。",
    summaryJa:
      "I am、he・she・it is、you・we・they are が基本です。否定はnot、質問はbe動詞を先頭に置きます。",
    topicTags: ["be-verb", "sentence-basics"],
    prerequisiteUnitId: "S0-U8",
    exercises: [
      {
        prompt: "She ___ a teacher. の空所に入る語を選んでください。",
        choices: ["am", "is", "are", "do"],
        answer: 1,
        explanation: "sheは一人の人を表すので、be動詞はisです。",
        hint: "he・sheの後ろに置くbe動詞です。",
        targetSkills: ["grammar"],
        targetMasteryDimensions: ["recall", "context"],
        diagnostic: { area: "beVerb", level: "standard" },
      },
      {
        prompt: "They ___ at the station. の空所に入る語を選んでください。",
        choices: ["am", "is", "are", "does"],
        answer: 2,
        explanation: "theyは複数を表すので、be動詞はareです。",
        hint: "we・theyの後ろに置くbe動詞です。",
        targetSkills: ["grammar"],
        targetMasteryDimensions: ["recall", "context"],
      },
      {
        prompt: "「私は疲れていません。」に合う英文を選んでください。",
        choices: [
          "I am not tired.",
          "I not am tired.",
          "I is not tired.",
          "I do tired.",
        ],
        answer: 0,
        explanation: "be動詞の否定文は、amの後ろにnotを置いてI am not tired.とします。",
        hint: "notはbe動詞の後ろです。",
        targetSkills: ["grammar", "reading"],
        targetMasteryDimensions: ["recall", "context"],
      },
      {
        prompt: "「彼は元気ですか。」に合う英文を選んでください。",
        choices: ["He is fine?", "Is he fine?", "Does he fine?", "Are he fine?"],
        answer: 1,
        explanation: "be動詞の質問ではisを先頭に置き、Is he fine?とします。",
        hint: "肯定文He is ...のisを前へ移します。",
        targetSkills: ["grammar"],
        targetMasteryDimensions: ["recall", "context"],
      },
      {
        prompt: "Are you hungry? への否定の返事を選んでください。",
        choices: ["No, I am not.", "No, you are.", "No, it is not.", "I no hungry."],
        answer: 0,
        explanation: "Are you ...?への否定の返事はNo, I am not.です。",
        hint: "質問のyouを返事ではIに変えます。",
        targetSkills: ["grammar", "speaking"],
        targetMasteryDimensions: ["context", "recall"],
      },
    ],
  },
  {
    stage: 1,
    unitId: "S1-U2",
    order: 2,
    titleJa: "一般動詞で毎日を話す",
    descriptionJa: "like・have・play・studyを使い、普段の行動を表します。",
    objectivesJa: [
      "主語の後ろに一般動詞を置いて文を作れる",
      "he・sheの文で動詞にsが付くことを理解できる",
    ],
    explanationJa:
      "一般動詞は「好き」「持っている」「する」などの動作や状態を表します。heやsheが主語の現在形では、動詞にsを付けます。",
    examples: [
      { en: "I play tennis.", ja: "私はテニスをします。" },
      { en: "She studies English.", ja: "彼女は英語を勉強します。" },
    ],
    recallJa:
      "I like、I have、I playの後ろに、自分に合う語を一つずつ足して言ってみましょう。",
    summaryJa:
      "I・you・we・theyでは動詞の基本形、he・sheではlikesやplaysのような形を使います。",
    topicTags: ["present-simple", "general-verbs"],
    prerequisiteUnitId: "S1-U1",
    exercises: [
      {
        prompt: "I ___ music. の空所に「好きです」を表す語を選んでください。",
        choices: ["like", "likes", "am", "is"],
        answer: 0,
        explanation: "主語がIなので、一般動詞の基本形likeを使います。",
        hint: "Iの後ろでは動詞にsを付けません。",
        targetSkills: ["grammar", "vocabulary"],
        targetMasteryDimensions: ["recall", "context"],
        diagnostic: { area: "generalVerb", level: "standard" },
      },
      {
        prompt: "He ___ soccer after school. の空所に入る語を選んでください。",
        choices: ["play", "plays", "playing", "are"],
        answer: 1,
        explanation: "主語がheなので、現在形のplayにsを付けてplaysとします。",
        hint: "heの文では動詞の形が少し変わります。",
        targetSkills: ["grammar"],
        targetMasteryDimensions: ["recall", "context"],
      },
      {
        prompt: "「私たちは英語を勉強します。」に合う英文を選んでください。",
        choices: [
          "We studies English.",
          "We study English.",
          "We are study English.",
          "We studying English.",
        ],
        answer: 1,
        explanation: "主語がweなので、一般動詞は基本形studyを使います。",
        hint: "weの後ろではstudyにsを付けません。",
        targetSkills: ["grammar", "reading"],
        targetMasteryDimensions: ["recall", "context"],
      },
      {
        prompt: "She ___ a red bag. の空所に「持っています」を表す語を選んでください。",
        choices: ["have", "has", "is have", "having"],
        answer: 1,
        explanation: "haveは、主語がsheのときhasという形になります。",
        hint: "haveの三人称単数形は不規則です。",
        targetSkills: ["grammar", "vocabulary"],
        targetMasteryDimensions: ["recall", "context"],
      },
      {
        prompt: "毎日の習慣を表す文を選んでください。",
        choices: [
          "I study math every day.",
          "I am math every day.",
          "Study I every day math.",
          "I every study am math.",
        ],
        answer: 0,
        explanation:
          "I study math every day.は「私は毎日数学を勉強します」という習慣の文です。",
        hint: "主語、動詞、目的語の順を探しましょう。",
        targetSkills: ["grammar", "reading"],
        targetMasteryDimensions: ["context"],
      },
    ],
  },
  {
    stage: 1,
    unitId: "S1-U3",
    order: 3,
    titleJa: "代名詞と「だれの」を表す語",
    descriptionJa: "I・you・he・she・we・theyとmy・your・his・herを整理します。",
    objectivesJa: [
      "人や物を代名詞で言い換えられる",
      "my・your・his・herで持ち主を表せる",
    ],
    explanationJa:
      "同じ名前を何度も言わず、I、you、he、she、we、theyで言い換えられます。名詞の前にmyなどを置くと持ち主を表せます。",
    examples: [
      { en: "Ken is my friend. He is kind.", ja: "ケンは私の友達です。彼は親切です。" },
      { en: "This is her book.", ja: "これは彼女の本です。" },
    ],
    recallJa:
      "my name、your book、his bag、her penを、意味を考えながら声に出してみましょう。",
    summaryJa:
      "heは男性一人、sheは女性一人、theyは複数を表します。myなどは名詞の前に置きます。",
    topicTags: ["pronouns", "possessives"],
    prerequisiteUnitId: "S1-U2",
    exercises: [
      {
        prompt: "Mai is a student. ___ is thirteen. の空所に入る語を選んでください。",
        choices: ["He", "She", "It", "They"],
        answer: 1,
        explanation: "Maiという女性一人を言い換えるのでSheを使います。",
        hint: "女性一人を表す代名詞です。",
        targetSkills: ["grammar", "reading"],
        targetMasteryDimensions: ["context", "recall"],
      },
      {
        prompt:
          "Ken and I are friends. ___ play tennis. の空所に入る語を選んでください。",
        choices: ["We", "He", "She", "It"],
        answer: 0,
        explanation: "Ken and Iは「ケンと私たち」なのでWeで言い換えます。",
        hint: "自分を含む複数の人を表します。",
        targetSkills: ["grammar"],
        targetMasteryDimensions: ["context", "recall"],
      },
      {
        prompt: "「私の名前」に合う英語を選んでください。",
        choices: ["I name", "me name", "my name", "mine names"],
        answer: 2,
        explanation: "名詞nameの前には、所有を表すmyを置いてmy nameとします。",
        hint: "myは「私の」です。",
        targetSkills: ["grammar", "vocabulary"],
        targetMasteryDimensions: ["recognition", "recall"],
      },
      {
        prompt: "This is Aya's bag. It is ___ bag. の空所に入る語を選んでください。",
        choices: ["his", "her", "your", "our"],
        answer: 1,
        explanation: "Ayaの持ち物なので、女性の「彼女の」を表すherを使います。",
        hint: "sheに対応する所有の語です。",
        targetSkills: ["grammar", "reading"],
        targetMasteryDimensions: ["context"],
      },
      {
        prompt: "話し相手の本を指して「あなたの本」と言う表現を選んでください。",
        choices: ["your book", "you book", "his book", "my books"],
        answer: 0,
        explanation: "話し相手の持ち物にはyourを使い、your bookとします。",
        hint: "yourは「あなたの」です。",
        targetSkills: ["grammar", "vocabulary"],
        targetMasteryDimensions: ["recall"],
      },
    ],
  },
  {
    stage: 1,
    unitId: "S1-U4",
    order: 4,
    titleJa: "a・anと複数形を使う",
    descriptionJa: "一つの物、複数の物、近くと遠くを表す語を学びます。",
    objectivesJa: [
      "aとanを基本的に使い分けられる",
      "this・that・these・thoseの違いを理解できる",
    ],
    explanationJa:
      "一つの数えられる物にはaまたはanを付けます。近くの一つはthis、遠くの一つはthat、近くの複数はtheseです。",
    examples: [
      { en: "an apple", ja: "一つのりんご" },
      { en: "These are my shoes.", ja: "これらは私の靴です。" },
    ],
    recallJa:
      "a book、an egg、two books、these booksを、形の違いに注意して言ってみましょう。",
    summaryJa:
      "母音の音で始まる一語にはanを使います。複数形では名詞にsなどを付け、theseやthoseを使えます。",
    topicTags: ["articles", "plurals", "demonstratives"],
    prerequisiteUnitId: "S1-U3",
    exercises: [
      {
        prompt: "___ apple の空所に入る語を選んでください。",
        choices: ["a", "an", "two", "thee"],
        answer: 1,
        explanation: "appleは母音の音で始まるのでan appleとします。",
        hint: "appleの最初の音に注目します。",
        targetSkills: ["grammar"],
        targetMasteryDimensions: ["recall"],
      },
      {
        prompt: "___ book の空所に入る語を選んでください。",
        choices: ["a", "an", "are", "two"],
        answer: 0,
        explanation: "bookは子音の音で始まる一つの物なのでa bookです。",
        hint: "bookはbの音で始まります。",
        targetSkills: ["grammar"],
        targetMasteryDimensions: ["recall"],
      },
      {
        prompt: "boxの複数形を選んでください。",
        choices: ["boxs", "boxes", "boxies", "box"],
        answer: 1,
        explanation: "boxのようにxで終わる語にはesを付け、boxesとします。",
        hint: "sだけでなくesを付けます。",
        targetSkills: ["grammar", "vocabulary"],
        targetMasteryDimensions: ["spelling", "recall"],
      },
      {
        prompt: "近くにある一冊の本を指す語を選んでください。",
        choices: ["this book", "that book", "these book", "those books"],
        answer: 0,
        explanation: "近くの一つの物にはthisを使い、this bookとします。",
        hint: "近く・一つの組み合わせです。",
        targetSkills: ["grammar", "vocabulary"],
        targetMasteryDimensions: ["context"],
      },
      {
        prompt: "遠くにある複数の星を表す語を選んでください。",
        choices: ["this star", "that stars", "these star", "those stars"],
        answer: 3,
        explanation: "遠くの複数にはthoseを使い、名詞も複数形starsにします。",
        hint: "遠く・複数の組み合わせです。",
        targetSkills: ["grammar", "vocabulary"],
        targetMasteryDimensions: ["context", "recall"],
      },
    ],
  },
  {
    stage: 1,
    unitId: "S1-U5",
    order: 5,
    titleJa: "疑問詞で詳しく尋ねる",
    descriptionJa: "what・who・where・when・howを場面に合わせて使います。",
    objectivesJa: [
      "尋ねたい内容に合う疑問詞を選べる",
      "疑問詞を文の先頭に置いて質問を作れる",
    ],
    explanationJa:
      "whatは物や内容、whoは人、whereは場所、whenは時、howは方法や様子を尋ねます。知りたい情報に合わせて選びます。",
    examples: [
      { en: "Where is the library?", ja: "図書館はどこですか。" },
      { en: "How are you?", ja: "お元気ですか。" },
    ],
    recallJa:
      "「何・だれ・どこ・いつ・どのように」に対応する英語を、順番に思い出しましょう。",
    summaryJa:
      "疑問詞は知りたい情報の種類を示します。what、who、where、when、howを質問の先頭に置きます。",
    topicTags: ["question-words", "information-questions"],
    prerequisiteUnitId: "S1-U4",
    exercises: [
      {
        prompt: "___ is your name? の空所に入る疑問詞を選んでください。",
        choices: ["Who", "What", "Where", "When"],
        answer: 1,
        explanation: "名前という内容を尋ねるのでWhat is your name?とします。",
        hint: "「何」を表す疑問詞です。",
        targetSkills: ["grammar"],
        targetMasteryDimensions: ["context", "recall"],
        diagnostic: { area: "questions", level: "standard" },
      },
      {
        prompt: "___ is that man? 「あの男性はだれですか。」の空所を選んでください。",
        choices: ["Who", "What", "When", "How"],
        answer: 0,
        explanation: "人がだれかを尋ねるのでWhoを使います。",
        hint: "人を尋ねる疑問詞です。",
        targetSkills: ["grammar"],
        targetMasteryDimensions: ["context", "recall"],
      },
      {
        prompt: "___ is the station? 「駅はどこですか。」の空所を選んでください。",
        choices: ["What", "Who", "Where", "When"],
        answer: 2,
        explanation: "場所を尋ねるのでWhereを使います。",
        hint: "場所を尋ねる疑問詞です。",
        targetSkills: ["grammar"],
        targetMasteryDimensions: ["context"],
      },
      {
        prompt:
          "___ is your birthday? 「誕生日はいつですか。」の空所を選んでください。",
        choices: ["When", "Where", "Who", "What color"],
        answer: 0,
        explanation: "時を尋ねるのでWhenを使います。",
        hint: "日や時刻を尋ねる疑問詞です。",
        targetSkills: ["grammar"],
        targetMasteryDimensions: ["context"],
      },
      {
        prompt: "How are you? に合う答えを選んでください。",
        choices: ["I'm fine, thank you.", "At seven.", "In Tokyo.", "My brother."],
        answer: 0,
        explanation:
          "How are you?は様子を尋ねる表現なので、I'm fine, thank you.が合います。",
        hint: "体調や気分を答えます。",
        targetSkills: ["reading", "speaking"],
        targetMasteryDimensions: ["context"],
      },
    ],
  },
  {
    stage: 1,
    unitId: "S1-U6",
    order: 6,
    titleJa: "canと命令文で頼む",
    descriptionJa: "できることを話し、短い指示や丁寧な依頼を作ります。",
    objectivesJa: ["canを使って能力を表せる", "動詞から始める短い指示とPleaseを使える"],
    explanationJa:
      "canの後ろには動詞の基本形を置きます。短い指示はOpen the door.のように動詞から始め、Pleaseを加えると丁寧になります。",
    examples: [
      { en: "I can swim.", ja: "私は泳げます。" },
      { en: "Please sit down.", ja: "座ってください。" },
    ],
    recallJa: "I can ...の後ろに、自分ができることを一つ入れて言ってみましょう。",
    summaryJa:
      "can＋動詞の基本形で「できる」を表します。命令文は動詞から始め、Pleaseで丁寧にできます。",
    topicTags: ["can", "imperatives", "requests"],
    prerequisiteUnitId: "S1-U5",
    exercises: [
      {
        prompt: "I can ___ English. の空所に入る語を選んでください。",
        choices: ["speak", "speaks", "speaking", "spoke"],
        answer: 0,
        explanation: "canの後ろには動詞の基本形speakを置きます。",
        hint: "canの後ろでは動詞にsを付けません。",
        targetSkills: ["grammar"],
        targetMasteryDimensions: ["recall", "context"],
      },
      {
        prompt: "「彼女は料理ができます。」に合う英文を選んでください。",
        choices: ["She can cooks.", "She cans cook.", "She can cook.", "She is cook."],
        answer: 2,
        explanation: "canは主語がsheでも形を変えず、後ろは基本形cookです。",
        hint: "canとcookの形は変えません。",
        targetSkills: ["grammar", "reading"],
        targetMasteryDimensions: ["recall", "context"],
      },
      {
        prompt: "Can you help me? への肯定の返事を選んでください。",
        choices: ["Yes, I can.", "Yes, I am.", "Yes, you do.", "I can not yes."],
        answer: 0,
        explanation: "Can you ...?への肯定の返事はYes, I can.です。",
        hint: "質問で使われたcanを返事にも使います。",
        targetSkills: ["grammar", "speaking"],
        targetMasteryDimensions: ["context", "recall"],
      },
      {
        prompt: "ドアを開けてほしいときの丁寧な表現を選んでください。",
        choices: [
          "Please open the door.",
          "You opening door.",
          "Can door open.",
          "Please the door is.",
        ],
        answer: 0,
        explanation: "Pleaseの後ろに動詞openを置き、Please open the door.とします。",
        hint: "Please＋動詞の順です。",
        targetSkills: ["grammar", "speaking"],
        targetMasteryDimensions: ["context"],
      },
      {
        prompt: "「ここで走らないでください。」に合う英文を選んでください。",
        choices: [
          "Not run here.",
          "Don't run here.",
          "No you running.",
          "Can't here run.",
        ],
        answer: 1,
        explanation: "否定の命令文はDon't＋動詞で作り、Don't run here.とします。",
        hint: "命令文の否定にはDon'tを使います。",
        targetSkills: ["grammar", "reading"],
        targetMasteryDimensions: ["recall", "context"],
      },
    ],
  },
  {
    stage: 1,
    unitId: "S1-U7",
    order: 7,
    titleJa: "there isと前置詞で場所を説明する",
    descriptionJa: "物の存在とin・on・under・nearを使った位置を表します。",
    objectivesJa: [
      "there isで一つの物があることを伝えられる",
      "基本の前置詞で物の位置を説明できる",
    ],
    explanationJa:
      "There is ...は「〜があります」という形です。場所はin、on、under、nearなどを使って具体的に示します。",
    examples: [
      { en: "There is a cup on the table.", ja: "テーブルの上にカップがあります。" },
      { en: "The cat is under the chair.", ja: "猫はいすの下にいます。" },
    ],
    recallJa:
      "机の上、箱の中、いすの下を英語でon the desk、in the box、under the chairと言ってみましょう。",
    summaryJa:
      "一つの存在はThere isで表せます。inは中、onは上、underは下、nearは近くです。",
    topicTags: ["there-is", "prepositions", "location"],
    prerequisiteUnitId: "S1-U6",
    exercises: [
      {
        prompt: "「机の上に本があります。」に合う英文を選んでください。",
        choices: [
          "There is a book on the desk.",
          "A desk is on a book.",
          "There are desk a book.",
          "Book there on desk.",
        ],
        answer: 0,
        explanation: "一冊の本の存在をThere isで表し、場所はon the deskとします。",
        hint: "There is＋物＋場所の順です。",
        targetSkills: ["grammar", "reading"],
        targetMasteryDimensions: ["context", "recall"],
      },
      {
        prompt:
          "The ball is ___ the box. 「ボールは箱の中です。」の空所を選んでください。",
        choices: ["on", "in", "under", "near"],
        answer: 1,
        explanation: "物の中を表す前置詞はinです。",
        hint: "箱の内側にある場面です。",
        targetSkills: ["grammar", "vocabulary"],
        targetMasteryDimensions: ["context"],
      },
      {
        prompt:
          "The bag is ___ the chair. 「かばんはいすの下です。」の空所を選んでください。",
        choices: ["under", "on", "in", "from"],
        answer: 0,
        explanation: "物の下を表す前置詞はunderです。",
        hint: "上下の「下」に注目します。",
        targetSkills: ["grammar", "vocabulary"],
        targetMasteryDimensions: ["context"],
      },
      {
        prompt: "「駅の近く」に合う英語を選んでください。",
        choices: [
          "under the station",
          "near the station",
          "in the station roof",
          "on station near",
        ],
        answer: 1,
        explanation: "nearは「〜の近く」を表すのでnear the stationです。",
        hint: "距離が近いことを表す前置詞です。",
        targetSkills: ["grammar", "vocabulary"],
        targetMasteryDimensions: ["recognition", "context"],
      },
      {
        prompt: "There is a clock on the wall. の意味を選んでください。",
        choices: [
          "壁の上に時計があります。",
          "時計の下に壁があります。",
          "壁の中に机があります。",
          "時計は駅の近くです。",
        ],
        answer: 0,
        explanation: "on the wallは「壁に接して掛かっている」位置を表します。",
        hint: "clockは時計、wallは壁です。",
        targetSkills: ["reading", "grammar"],
        targetMasteryDimensions: ["context"],
      },
    ],
  },
  {
    stage: 1,
    unitId: "S1-U8",
    order: 8,
    titleJa: "5文の自己紹介を作る",
    descriptionJa: "名前、出身、家族、好きなこと、できることをつなげます。",
    objectivesJa: [
      "既習の文型を使って5文以上の自己紹介を作れる",
      "短い自己紹介を読み、必要な情報を取り出せる",
    ],
    explanationJa:
      "一つの長い文にせず、短い文を順に並べると伝わりやすい自己紹介になります。最後にNice to meet you.を添えられます。",
    examples: [
      { en: "I am Sora. I am from Osaka.", ja: "私はソラです。大阪出身です。" },
      {
        en: "I like books. I can play the piano.",
        ja: "本が好きです。ピアノを弾けます。",
      },
    ],
    recallJa:
      "名前、出身、好きなもの、できること、結びのあいさつを、5文に分けて言ってみましょう。",
    summaryJa:
      "短い既習文を順に並べれば自己紹介を作れます。書いた後は主語と動詞を一文ずつ確認しましょう。",
    topicTags: ["self-introduction", "stage-project"],
    prerequisiteUnitId: "S1-U7",
    exercises: [
      {
        type: "readingQuestion",
        stimulus:
          "Hello. I am Riku. I am from Nagoya. I like soccer. I can cook. Nice to meet you.",
        prompt: "Rikuさんが好きなものを選んでください。",
        choices: ["soccer", "cooking", "music", "English"],
        answer: 0,
        explanation: "I like soccer.と書かれているので、好きなものはsoccerです。",
        hint: "likeの後ろを探しましょう。",
        targetSkills: ["reading"],
        targetMasteryDimensions: ["context"],
      },
      {
        prompt: "自己紹介の最初の文として自然なものを選んでください。",
        choices: ["I am Nao.", "Are you Nao?", "This Nao am.", "Nao is you."],
        answer: 0,
        explanation: "自分の名前はI am Nao.の形で伝えられます。",
        hint: "I amの後ろに名前を置きます。",
        targetSkills: ["writing", "speaking"],
        targetMasteryDimensions: ["recall", "context"],
      },
      {
        prompt: "「私は福岡出身です。」に合う英文を選んでください。",
        choices: [
          "I from Fukuoka.",
          "I am from Fukuoka.",
          "I am Fukuoka from.",
          "From I is Fukuoka.",
        ],
        answer: 1,
        explanation: "出身はI am from＋場所で表します。",
        hint: "amとfromの両方を使います。",
        targetSkills: ["writing", "grammar"],
        targetMasteryDimensions: ["recall", "context"],
      },
      {
        prompt: "「私は犬が好きです。」に合う英文を選んでください。",
        choices: ["I like dogs.", "I am dogs.", "Dogs like I.", "I can dogs."],
        answer: 0,
        explanation:
          "好きなものはI like＋名詞で表します。一般的な犬は複数形dogsが自然です。",
        hint: "likeの後ろに好きなものを置きます。",
        targetSkills: ["writing", "grammar"],
        targetMasteryDimensions: ["recall", "context"],
      },
      {
        prompt: "自己紹介の結びとして自然な表現を選んでください。",
        choices: [
          "Nice to meet you.",
          "What is this?",
          "Don't open it.",
          "Where is my bag?",
        ],
        answer: 0,
        explanation: "Nice to meet you.は自己紹介の結びに使える「はじめまして」です。",
        hint: "初対面のあいさつを選びましょう。",
        targetSkills: ["speaking", "vocabulary"],
        targetMasteryDimensions: ["context", "recall"],
      },
    ],
  },
] satisfies readonly UnitContentSeed[];

const generatedStage1Content = stage1Seeds.map(createUnitContent);

export const stage1Lessons = generatedStage1Content.map(({ lesson }) => lesson);
export const stage1Exercises = generatedStage1Content.flatMap(
  ({ exercises }) => exercises,
);
