import type { VocabularyItem } from "../../infrastructure/content/schemas";
import { ORIGINAL_CONTENT_SOURCE, type CurriculumStage } from "./factories";

type PartOfSpeech = VocabularyItem["partOfSpeech"];

interface VocabularySeedOptions {
  lemma?: string;
  synonyms?: readonly string[];
  antonyms?: readonly string[];
  confusionGroupIds?: readonly string[];
  extraTags?: readonly string[];
}

interface VocabularySeed {
  headword: string;
  partOfSpeech: PartOfSpeech;
  meaningJa: string;
  exampleEn: string;
  exampleJa: string;
  topic: string;
  collocation: string;
  options: VocabularySeedOptions;
}

interface StageVocabularySeeds {
  stage: CurriculumStage;
  entries: readonly VocabularySeed[];
}

function vocab(
  headword: string,
  partOfSpeech: PartOfSpeech,
  meaningJa: string,
  exampleEn: string,
  exampleJa: string,
  topic: string,
  collocation: string,
  options: VocabularySeedOptions = {},
): VocabularySeed {
  return {
    headword,
    partOfSpeech,
    meaningJa,
    exampleEn,
    exampleJa,
    topic,
    collocation,
    options,
  };
}

const stageVocabularySeeds: readonly StageVocabularySeeds[] = [
  {
    stage: 0,
    entries: [
      vocab(
        "hello",
        "other",
        "こんにちは",
        "Hello, I am Emi.",
        "こんにちは、私はエミです。",
        "greeting",
        "say hello",
        { synonyms: ["hi"] },
      ),
      vocab(
        "goodbye",
        "other",
        "さようなら",
        "Goodbye, see you tomorrow.",
        "さようなら、また明日。",
        "greeting",
        "say goodbye",
      ),
      vocab(
        "yes",
        "other",
        "はい",
        "Yes, this is my book.",
        "はい、これは私の本です。",
        "response",
        "say yes",
        { antonyms: ["no"] },
      ),
      vocab(
        "no",
        "other",
        "いいえ",
        "No, this is not mine.",
        "いいえ、これは私のものではありません。",
        "response",
        "say no",
        { antonyms: ["yes"] },
      ),
      vocab(
        "please",
        "other",
        "お願いします",
        "Please open the book.",
        "本を開いてください。",
        "politeness",
        "please help",
      ),
      vocab(
        "thank you",
        "phrase",
        "ありがとう",
        "Thank you for your help.",
        "手伝ってくれてありがとう。",
        "politeness",
        "say thank you",
      ),
      vocab(
        "sorry",
        "other",
        "ごめんなさい",
        "Sorry, I am late.",
        "ごめんなさい、遅れました。",
        "politeness",
        "say sorry",
      ),
      vocab(
        "name",
        "noun",
        "名前",
        "My name is Yui.",
        "私の名前はユイです。",
        "personal-information",
        "your name",
      ),
      vocab(
        "number",
        "noun",
        "数字、番号",
        "The number is three.",
        "その数字は3です。",
        "numbers",
        "phone number",
      ),
      vocab(
        "day",
        "noun",
        "日、1日",
        "It is a sunny day.",
        "晴れた日です。",
        "time",
        "every day",
      ),
      vocab(
        "time",
        "noun",
        "時刻、時間",
        "What time is it?",
        "何時ですか。",
        "time",
        "have time",
      ),
      vocab(
        "family",
        "noun",
        "家族",
        "This is my family.",
        "こちらは私の家族です。",
        "people",
        "my family",
      ),
      vocab(
        "friend",
        "noun",
        "友達",
        "Ken is my friend.",
        "ケンは私の友達です。",
        "people",
        "good friend",
      ),
      vocab(
        "home",
        "noun",
        "家、自宅",
        "I am at home.",
        "私は家にいます。",
        "places",
        "at home",
      ),
      vocab(
        "school",
        "noun",
        "学校",
        "This is my school.",
        "これは私の学校です。",
        "places",
        "go to school",
      ),
      vocab(
        "book",
        "noun",
        "本",
        "This is a book.",
        "これは本です。",
        "learning",
        "read a book",
      ),
      vocab(
        "water",
        "noun",
        "水",
        "I drink water.",
        "私は水を飲みます。",
        "food-drink",
        "drink water",
      ),
      vocab(
        "food",
        "noun",
        "食べ物",
        "This food is good.",
        "この食べ物はおいしいです。",
        "food-drink",
        "healthy food",
      ),
      vocab(
        "like",
        "verb",
        "好きである",
        "I like cats.",
        "私は猫が好きです。",
        "feelings",
        "like music",
      ),
      vocab(
        "happy",
        "adjective",
        "うれしい、幸せな",
        "I am happy.",
        "私はうれしいです。",
        "feelings",
        "feel happy",
        { antonyms: ["sad"] },
      ),
    ],
  },
  {
    stage: 1,
    entries: [
      vocab(
        "study",
        "verb",
        "勉強する",
        "I study English every day.",
        "私は毎日英語を勉強します。",
        "learning",
        "study English",
      ),
      vocab(
        "work",
        "verb",
        "働く",
        "I work at a small shop.",
        "私は小さな店で働いています。",
        "work",
        "work at a shop",
      ),
      vocab(
        "live",
        "verb",
        "住む",
        "We live near the station.",
        "私たちは駅の近くに住んでいます。",
        "home",
        "live in Japan",
      ),
      vocab(
        "have",
        "verb",
        "持っている",
        "I have a blue bag.",
        "私は青いかばんを持っています。",
        "daily-action",
        "have a bag",
      ),
      vocab(
        "play",
        "verb",
        "遊ぶ、競技をする",
        "They play tennis after school.",
        "彼らは放課後にテニスをします。",
        "sports",
        "play tennis",
      ),
      vocab(
        "eat",
        "verb",
        "食べる",
        "We eat breakfast at seven.",
        "私たちは7時に朝食を食べます。",
        "food-drink",
        "eat breakfast",
      ),
      vocab(
        "drink",
        "verb",
        "飲む",
        "I drink tea every morning.",
        "私は毎朝お茶を飲みます。",
        "food-drink",
        "drink tea",
      ),
      vocab(
        "go",
        "verb",
        "行く",
        "I go to school by bus.",
        "私はバスで学校へ行きます。",
        "movement",
        "go to school",
        { antonyms: ["come"] },
      ),
      vocab(
        "come",
        "verb",
        "来る",
        "Please come to my house.",
        "私の家に来てください。",
        "movement",
        "come home",
        { antonyms: ["go"] },
      ),
      vocab(
        "make",
        "verb",
        "作る",
        "We make dinner together.",
        "私たちは一緒に夕食を作ります。",
        "daily-action",
        "make dinner",
      ),
      vocab(
        "help",
        "verb",
        "助ける、手伝う",
        "I help my mother at home.",
        "私は家で母を手伝います。",
        "support",
        "help a friend",
      ),
      vocab(
        "busy",
        "adjective",
        "忙しい",
        "She is busy today.",
        "彼女は今日忙しいです。",
        "condition",
        "be busy",
      ),
      vocab(
        "tired",
        "adjective",
        "疲れた",
        "I am tired after work.",
        "私は仕事の後で疲れています。",
        "condition",
        "feel tired",
      ),
      vocab(
        "new",
        "adjective",
        "新しい",
        "This is my new notebook.",
        "これは私の新しいノートです。",
        "description",
        "new book",
        { antonyms: ["old"] },
      ),
      vocab(
        "old",
        "adjective",
        "古い、年を取った",
        "That house is very old.",
        "あの家はとても古いです。",
        "description",
        "old house",
        { antonyms: ["new"] },
      ),
      vocab(
        "morning",
        "noun",
        "朝",
        "I study English every morning.",
        "私は毎朝英語を勉強します。",
        "time",
        "every morning",
      ),
      vocab(
        "evening",
        "noun",
        "夕方、晩",
        "We walk in the evening.",
        "私たちは夕方に歩きます。",
        "time",
        "in the evening",
      ),
      vocab(
        "every day",
        "phrase",
        "毎日",
        "I read a book every day.",
        "私は毎日本を読みます。",
        "time",
        "study every day",
      ),
      vocab(
        "after school",
        "phrase",
        "放課後",
        "We play soccer after school.",
        "私たちは放課後にサッカーをします。",
        "school",
        "practice after school",
      ),
      vocab(
        "can",
        "other",
        "〜できる",
        "I can cook rice.",
        "私はご飯を炊けます。",
        "ability",
        "can cook",
      ),
    ],
  },
  {
    stage: 2,
    entries: [
      vocab(
        "yesterday",
        "adverb",
        "昨日",
        "I visited my aunt yesterday.",
        "私は昨日おばを訪ねました。",
        "past-time",
        "yesterday morning",
      ),
      vocab(
        "tomorrow",
        "adverb",
        "明日",
        "We will leave tomorrow.",
        "私たちは明日出発します。",
        "future-time",
        "tomorrow morning",
      ),
      vocab(
        "visit",
        "verb",
        "訪れる",
        "I will visit Kyoto next week.",
        "私は来週京都を訪れます。",
        "travel",
        "visit a city",
      ),
      vocab(
        "travel",
        "verb",
        "旅行する",
        "They travel by train in summer.",
        "彼らは夏に列車で旅行します。",
        "travel",
        "travel by train",
      ),
      vocab(
        "arrive",
        "verb",
        "到着する",
        "We arrive at the station at nine.",
        "私たちは9時に駅へ到着します。",
        "travel",
        "arrive at the station",
      ),
      vocab(
        "leave",
        "verb",
        "出発する、去る",
        "The bus will leave at ten.",
        "そのバスは10時に出発します。",
        "travel",
        "leave home",
      ),
      vocab(
        "borrow",
        "verb",
        "借りる",
        "Can I borrow your pen?",
        "あなたのペンを借りてもよいですか。",
        "daily-action",
        "borrow a book",
        { confusionGroupIds: ["confusion-borrow-lend"] },
      ),
      vocab(
        "lend",
        "verb",
        "貸す",
        "I can lend you this book.",
        "私はあなたにこの本を貸せます。",
        "daily-action",
        "lend a book",
        { confusionGroupIds: ["confusion-borrow-lend"] },
      ),
      vocab(
        "plan",
        "verb",
        "計画する",
        "We plan to visit Nara.",
        "私たちは奈良を訪れる計画です。",
        "planning",
        "plan a trip",
      ),
      vocab(
        "decide",
        "verb",
        "決める",
        "We decide to take the early train.",
        "私たちは早い列車に乗ることを決めます。",
        "planning",
        "decide to go",
      ),
      vocab(
        "weather",
        "noun",
        "天気",
        "The weather was warm yesterday.",
        "昨日は暖かい天気でした。",
        "weather",
        "good weather",
      ),
      vocab(
        "station",
        "noun",
        "駅",
        "Meet me at the station tomorrow.",
        "明日駅で会いましょう。",
        "travel",
        "train station",
      ),
      vocab(
        "ticket",
        "noun",
        "切符、チケット",
        "I bought a train ticket.",
        "私は列車の切符を買いました。",
        "travel",
        "buy a ticket",
      ),
      vocab(
        "trip",
        "noun",
        "旅行",
        "Our trip was short but fun.",
        "私たちの旅行は短かったですが楽しかったです。",
        "travel",
        "school trip",
      ),
      vocab(
        "carry",
        "verb",
        "運ぶ、持ち歩く",
        "I carry a small bag.",
        "私は小さなかばんを持ち歩きます。",
        "daily-action",
        "carry a bag",
      ),
      vocab(
        "cheap",
        "adjective",
        "安い",
        "This ticket is cheap.",
        "この切符は安いです。",
        "shopping",
        "cheap ticket",
        { antonyms: ["expensive"] },
      ),
      vocab(
        "fast",
        "adjective",
        "速い",
        "This train is fast.",
        "この列車は速いです。",
        "description",
        "fast train",
        { antonyms: ["slow"] },
      ),
      vocab(
        "slow",
        "adjective",
        "遅い、ゆっくりした",
        "The bus was slow today.",
        "今日そのバスは遅かったです。",
        "description",
        "slow bus",
        { antonyms: ["fast"] },
      ),
      vocab(
        "during",
        "preposition",
        "〜の間に",
        "We talked during the trip.",
        "私たちは旅行中に話しました。",
        "time",
        "during the day",
      ),
      vocab(
        "next week",
        "phrase",
        "来週",
        "I will visit my friend next week.",
        "私は来週友達を訪ねます。",
        "future-time",
        "travel next week",
      ),
    ],
  },
  {
    stage: 3,
    entries: [
      vocab(
        "environment",
        "noun",
        "環境",
        "We should protect the environment.",
        "私たちは環境を守るべきです。",
        "environment",
        "protect the environment",
      ),
      vocab(
        "protect",
        "verb",
        "守る",
        "Trees protect the town from strong winds.",
        "木々は強い風から町を守ります。",
        "environment",
        "protect nature",
      ),
      vocab(
        "recycle",
        "verb",
        "再利用する",
        "We recycle paper at school.",
        "私たちは学校で紙を再利用します。",
        "environment",
        "recycle paper",
      ),
      vocab(
        "experience",
        "noun",
        "経験",
        "Travel can be a useful experience.",
        "旅行は役立つ経験になり得ます。",
        "learning",
        "useful experience",
      ),
      vocab(
        "continue",
        "verb",
        "続ける",
        "Please continue reading the story.",
        "その物語を読み続けてください。",
        "learning",
        "continue reading",
      ),
      vocab(
        "already",
        "adverb",
        "すでに",
        "I have already finished my homework.",
        "私はすでに宿題を終えました。",
        "grammar-time",
        "already finished",
      ),
      vocab(
        "yet",
        "adverb",
        "まだ、もう",
        "She has not arrived yet.",
        "彼女はまだ到着していません。",
        "grammar-time",
        "not yet",
      ),
      vocab(
        "since",
        "preposition",
        "〜以来",
        "I have lived here since 2020.",
        "私は2020年からここに住んでいます。",
        "grammar-time",
        "since last year",
      ),
      vocab(
        "quiet",
        "adjective",
        "静かな",
        "This room is quiet in the morning.",
        "この部屋は朝は静かです。",
        "description",
        "quiet room",
        { confusionGroupIds: ["confusion-quiet-quite"] },
      ),
      vocab(
        "quite",
        "adverb",
        "かなり",
        "The test was quite easy.",
        "そのテストはかなり簡単でした。",
        "degree",
        "quite easy",
        { confusionGroupIds: ["confusion-quiet-quite"] },
      ),
      vocab(
        "important",
        "adjective",
        "重要な",
        "Sleep is important for our health.",
        "睡眠は健康にとって重要です。",
        "health",
        "important reason",
      ),
      vocab(
        "different",
        "adjective",
        "異なる",
        "Their ideas are different from ours.",
        "彼らの考えは私たちのものと異なります。",
        "description",
        "different from",
      ),
      vocab(
        "information",
        "noun",
        "情報",
        "This website has useful information.",
        "このウェブサイトには役立つ情報があります。",
        "communication",
        "useful information",
      ),
      vocab(
        "language",
        "noun",
        "言語",
        "English is a language used in many countries.",
        "英語は多くの国で使われる言語です。",
        "culture",
        "foreign language",
      ),
      vocab(
        "culture",
        "noun",
        "文化",
        "Food tells us about local culture.",
        "食べ物は地域の文化を伝えてくれます。",
        "culture",
        "local culture",
      ),
      vocab(
        "community",
        "noun",
        "地域社会",
        "Our community has a small library.",
        "私たちの地域には小さな図書館があります。",
        "society",
        "local community",
      ),
      vocab(
        "health",
        "noun",
        "健康",
        "Walking every day is good for health.",
        "毎日歩くことは健康によいです。",
        "health",
        "good health",
      ),
      vocab(
        "problem",
        "noun",
        "問題",
        "We found a problem in the plan.",
        "私たちは計画に問題を見つけました。",
        "problem-solving",
        "solve a problem",
      ),
      vocab(
        "solution",
        "noun",
        "解決策",
        "They discussed a simple solution.",
        "彼らは簡単な解決策を話し合いました。",
        "problem-solving",
        "find a solution",
      ),
      vocab(
        "possible",
        "adjective",
        "可能な",
        "It is possible to learn from mistakes.",
        "間違いから学ぶことは可能です。",
        "possibility",
        "if possible",
      ),
    ],
  },
  {
    stage: 4,
    entries: [
      vocab(
        "accept",
        "verb",
        "受け入れる",
        "I accept your kind offer.",
        "私はあなたの親切な申し出を受け入れます。",
        "communication",
        "accept an offer",
        { confusionGroupIds: ["confusion-accept-except"] },
      ),
      vocab(
        "except",
        "preposition",
        "〜を除いて",
        "The shop is open every day except Monday.",
        "その店は月曜日を除いて毎日開いています。",
        "exception",
        "everyone except me",
        { confusionGroupIds: ["confusion-accept-except"] },
      ),
      vocab(
        "include",
        "verb",
        "含む",
        "The price will include breakfast.",
        "その料金には朝食が含まれます。",
        "information",
        "include breakfast",
      ),
      vocab(
        "provide",
        "verb",
        "提供する",
        "The center can provide free advice.",
        "その施設は無料の助言を提供できます。",
        "service",
        "provide information",
      ),
      vocab(
        "improve",
        "verb",
        "改善する、上達させる",
        "Daily practice can improve your writing.",
        "毎日の練習は作文力を伸ばせます。",
        "change",
        "improve skills",
      ),
      vocab(
        "reduce",
        "verb",
        "減らす",
        "We can reduce waste by reusing bags.",
        "袋を再利用してごみを減らせます。",
        "change",
        "reduce waste",
        { antonyms: ["increase"] },
      ),
      vocab(
        "increase",
        "verb",
        "増やす、増える",
        "The town will increase bus services.",
        "その町はバスの便を増やします。",
        "change",
        "increase access",
        { antonyms: ["reduce"] },
      ),
      vocab(
        "choose",
        "verb",
        "選ぶ",
        "You can choose one of these courses.",
        "これらの講座から一つ選べます。",
        "decision",
        "choose a course",
      ),
      vocab(
        "avoid",
        "verb",
        "避ける",
        "I walk early to avoid heavy traffic.",
        "激しい交通を避けるため早く歩きます。",
        "decision",
        "avoid waste",
      ),
      vocab(
        "allow",
        "verb",
        "許可する、可能にする",
        "This pass will allow you to enter.",
        "この許可証があれば入場できます。",
        "rules",
        "allow access",
      ),
      vocab(
        "purpose",
        "noun",
        "目的",
        "The purpose of this meeting is to share ideas.",
        "この会議の目的は考えを共有することです。",
        "reasoning",
        "main purpose",
      ),
      vocab(
        "result",
        "noun",
        "結果",
        "The result was better than we expected.",
        "結果は予想よりよいものでした。",
        "reasoning",
        "test result",
      ),
      vocab(
        "condition",
        "noun",
        "状態、条件",
        "The road is in good condition.",
        "その道路はよい状態です。",
        "description",
        "under this condition",
      ),
      vocab(
        "likely",
        "adjective",
        "〜しそうな、可能性が高い",
        "It is likely to rain this evening.",
        "今晩は雨が降りそうです。",
        "possibility",
        "be likely to",
      ),
      vocab(
        "perhaps",
        "adverb",
        "たぶん",
        "Perhaps we can meet after lunch.",
        "たぶん昼食後に会えます。",
        "possibility",
        "perhaps because",
      ),
      vocab(
        "instead",
        "adverb",
        "代わりに",
        "The bus was full, so I walked instead.",
        "バスが満員だったので、代わりに歩きました。",
        "connector",
        "use instead",
      ),
      vocab(
        "although",
        "conjunction",
        "〜だけれども",
        "Although it was cold, we played outside.",
        "寒かったけれども、私たちは外で遊びました。",
        "connector",
        "although difficult",
      ),
      vocab(
        "however",
        "adverb",
        "しかしながら",
        "The task was difficult. However, we finished it.",
        "課題は難しかったです。しかし、終えました。",
        "connector",
        "however, we continued",
      ),
      vocab(
        "therefore",
        "adverb",
        "そのため",
        "The road was closed. Therefore, we took another route.",
        "道路が閉鎖されていました。そのため、別の道を通りました。",
        "connector",
        "therefore necessary",
      ),
      vocab(
        "according to",
        "phrase",
        "〜によると",
        "According to the guide, the museum closes at five.",
        "案内によると、その博物館は5時に閉まります。",
        "source",
        "according to the report",
      ),
    ],
  },
  {
    stage: 5,
    entries: [
      vocab(
        "rise",
        "verb",
        "上がる、増える",
        "Prices may rise when supplies are low.",
        "供給が少ないと価格が上がることがあります。",
        "change",
        "prices rise",
        { confusionGroupIds: ["confusion-rise-raise"] },
      ),
      vocab(
        "raise",
        "verb",
        "上げる、集める",
        "The school will raise money for new books.",
        "学校は新しい本のために資金を集めます。",
        "change",
        "raise money",
        { confusionGroupIds: ["confusion-rise-raise"] },
      ),
      vocab(
        "benefit",
        "noun",
        "利点、恩恵",
        "One benefit of walking is better health.",
        "歩くことの利点の一つは健康の改善です。",
        "argument",
        "major benefit",
        { synonyms: ["advantage"] },
      ),
      vocab(
        "disadvantage",
        "noun",
        "不利な点",
        "A disadvantage of this plan is its cost.",
        "この計画の不利な点は費用です。",
        "argument",
        "main disadvantage",
        { antonyms: ["advantage"] },
      ),
      vocab(
        "access",
        "noun",
        "利用する機会、接続",
        "The program gives children access to books.",
        "その事業は子どもに本を利用する機会を与えます。",
        "society",
        "access to education",
      ),
      vocab(
        "education",
        "noun",
        "教育",
        "Online education can reach people in remote areas.",
        "オンライン教育は遠い地域の人にも届きます。",
        "education",
        "online education",
      ),
      vocab(
        "technology",
        "noun",
        "技術",
        "Technology helps us share information quickly.",
        "技術は情報をすばやく共有する助けになります。",
        "technology",
        "new technology",
      ),
      vocab(
        "society",
        "noun",
        "社会",
        "Public libraries play an important role in society.",
        "公共図書館は社会で重要な役割を果たします。",
        "society",
        "modern society",
      ),
      vocab(
        "local",
        "adjective",
        "地域の、地元の",
        "We buy vegetables from local farmers.",
        "私たちは地元の農家から野菜を買います。",
        "community",
        "local people",
        { antonyms: ["global"] },
      ),
      vocab(
        "global",
        "adjective",
        "世界的な",
        "Climate change is a global problem.",
        "気候変動は世界的な問題です。",
        "society",
        "global issue",
        { antonyms: ["local"] },
      ),
      vocab(
        "communicate",
        "verb",
        "意思を伝え合う",
        "Teams communicate online when members work remotely.",
        "メンバーが遠隔で働くとき、チームはオンラインで連絡します。",
        "communication",
        "communicate clearly",
      ),
      vocab(
        "compare",
        "verb",
        "比較する",
        "We compare the two plans before deciding.",
        "私たちは決める前に二つの計画を比較します。",
        "reasoning",
        "compare prices",
      ),
      vocab(
        "support",
        "verb",
        "支える、支持する",
        "The data support our main idea.",
        "そのデータは私たちの中心的な考えを支えます。",
        "argument",
        "support an idea",
      ),
      vocab(
        "reason",
        "noun",
        "理由",
        "One reason is that the service is convenient.",
        "理由の一つは、そのサービスが便利なことです。",
        "argument",
        "main reason",
      ),
      vocab(
        "example",
        "noun",
        "例",
        "This town is a good example of environmentally friendly design.",
        "この町は環境に配慮した設計のよい例です。",
        "argument",
        "give an example",
      ),
      vocab(
        "opinion",
        "noun",
        "意見",
        "Please explain your opinion with a reason.",
        "理由を添えて意見を説明してください。",
        "argument",
        "share an opinion",
      ),
      vocab(
        "suggest",
        "verb",
        "示す、提案する",
        "The results suggest that the program works.",
        "結果は、その事業が機能していることを示しています。",
        "argument",
        "suggest a plan",
      ),
      vocab(
        "require",
        "verb",
        "必要とする",
        "This job may require careful planning.",
        "この仕事には慎重な計画が必要かもしれません。",
        "work",
        "require time",
      ),
      vocab(
        "public",
        "adjective",
        "公共の",
        "Public transport can reduce city traffic.",
        "公共交通は都市の交通量を減らせます。",
        "society",
        "public transport",
      ),
      vocab(
        "renewable energy",
        "phrase",
        "再生可能エネルギー",
        "Renewable energy can reduce harmful emissions.",
        "再生可能エネルギーは有害な排出を減らせます。",
        "environment",
        "use renewable energy",
      ),
    ],
  },
  {
    stage: 6,
    entries: [
      vocab(
        "issue",
        "noun",
        "問題、論点",
        "The article discusses a local housing issue.",
        "その記事は地域の住宅問題を論じています。",
        "argument",
        "important issue",
      ),
      vocab(
        "effect",
        "noun",
        "影響、効果",
        "The new policy had a positive effect on recycling.",
        "新しい方針はリサイクルによい影響を与えました。",
        "cause-effect",
        "positive effect",
        { confusionGroupIds: ["confusion-affect-effect"] },
      ),
      vocab(
        "cause",
        "verb",
        "引き起こす",
        "Heavy traffic can cause air pollution.",
        "激しい交通は大気汚染を引き起こすことがあります。",
        "cause-effect",
        "cause a problem",
      ),
      vocab(
        "opportunity",
        "noun",
        "機会",
        "The program gives students an opportunity to volunteer.",
        "その事業は生徒にボランティアをする機会を与えます。",
        "society",
        "learning opportunity",
      ),
      vocab(
        "challenge",
        "noun",
        "課題、挑戦",
        "Finding enough workers remains a serious challenge.",
        "十分な働き手を見つけることは深刻な課題です。",
        "problem-solving",
        "face a challenge",
      ),
      vocab(
        "resource",
        "noun",
        "資源",
        "Clean water is an important natural resource.",
        "きれいな水は重要な天然資源です。",
        "environment",
        "natural resource",
      ),
      vocab(
        "policy",
        "noun",
        "方針、政策",
        "The city changed its transport policy last year.",
        "その市は昨年交通政策を変更しました。",
        "society",
        "public policy",
      ),
      vocab(
        "research",
        "noun",
        "研究、調査",
        "Recent research shows that sleep supports learning.",
        "最近の研究は睡眠が学習を支えると示しています。",
        "research",
        "conduct research",
      ),
      vocab(
        "evidence",
        "noun",
        "根拠、証拠",
        "The report provides evidence for the proposed change.",
        "その報告書は提案された変更の根拠を示しています。",
        "research",
        "strong evidence",
      ),
      vocab(
        "responsible",
        "adjective",
        "責任がある",
        "Companies are responsible for protecting customer data.",
        "企業には顧客データを守る責任があります。",
        "responsibility",
        "be responsible for",
      ),
      vocab(
        "available",
        "adjective",
        "利用できる",
        "The service is available in five languages.",
        "そのサービスは5つの言語で利用できます。",
        "service",
        "widely available",
      ),
      vocab(
        "convenient",
        "adjective",
        "便利な",
        "Online booking is convenient for busy people.",
        "オンライン予約は忙しい人に便利です。",
        "service",
        "convenient way",
      ),
      vocab(
        "flexible",
        "adjective",
        "柔軟な",
        "A flexible schedule helps parents balance work and family.",
        "柔軟な予定は親が仕事と家庭を両立する助けになります。",
        "work",
        "flexible schedule",
      ),
      vocab(
        "prevent",
        "verb",
        "防ぐ",
        "Regular checks can prevent small problems from growing.",
        "定期的な確認は小さな問題の拡大を防げます。",
        "problem-solving",
        "prevent accidents",
      ),
      vocab(
        "participate in",
        "phrase",
        "〜に参加する",
        "Many residents participate in the yearly cleanup.",
        "多くの住民が毎年の清掃活動に参加します。",
        "community",
        "participate in an event",
      ),
      vocab(
        "in contrast",
        "phrase",
        "対照的に",
        "The first plan is costly. In contrast, the second is affordable.",
        "最初の案は高額です。対照的に二つ目は手頃です。",
        "connector",
        "in contrast to",
      ),
      vocab(
        "as a result",
        "phrase",
        "その結果",
        "The library stayed open later. As a result, more workers visited.",
        "図書館は遅くまで開館しました。その結果、より多くの働く人が訪れました。",
        "connector",
        "as a result of",
      ),
      vocab(
        "on the other hand",
        "phrase",
        "一方で",
        "Cars are convenient. On the other hand, they create pollution.",
        "車は便利です。一方で、汚染を生みます。",
        "connector",
        "on the other hand",
      ),
      vocab(
        "in conclusion",
        "phrase",
        "結論として",
        "In conclusion, the plan offers more benefits than risks.",
        "結論として、その計画は危険より多くの利点をもたらします。",
        "connector",
        "in conclusion",
      ),
      vocab(
        "affect",
        "verb",
        "影響を与える",
        "Weather changes can affect food production.",
        "天候の変化は食料生産に影響を与えることがあります。",
        "cause-effect",
        "affect people",
        { confusionGroupIds: ["confusion-affect-effect"] },
      ),
    ],
  },
];

function slugifyHeadword(headword: string): string {
  return headword
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function createVocabularyItem(
  stage: CurriculumStage,
  seed: VocabularySeed,
): VocabularyItem {
  const slug = slugifyHeadword(seed.headword);
  const id = `vocab-s${stage}-${slug}`;
  const usageTag = seed.headword.includes(" ") ? "form:phrase" : "form:word";

  return {
    id,
    schemaVersion: "1.0.0",
    contentRevision: 1,
    stage,
    headword: seed.headword,
    lemma: seed.options.lemma ?? seed.headword,
    partOfSpeech: seed.partOfSpeech,
    meanings: [
      {
        id: "primary",
        ja: seed.meaningJa,
        register: "neutral",
      },
    ],
    exampleSentences: [
      {
        id: `${id}-example-1`,
        en: seed.exampleEn,
        ja: seed.exampleJa,
        stage,
      },
    ],
    collocations: [seed.collocation],
    synonyms: [...(seed.options.synonyms ?? [])],
    antonyms: [...(seed.options.antonyms ?? [])],
    confusionGroupIds: [...(seed.options.confusionGroupIds ?? [])],
    tags: [
      "original",
      "vocabulary",
      `stage:${stage}`,
      `part-of-speech:${seed.partOfSpeech}`,
      `topic:${seed.topic}`,
      `search:${seed.topic}`,
      usageTag,
      ...(seed.options.extraTags ?? []),
    ],
    source: ORIGINAL_CONTENT_SOURCE,
  };
}

export const pilotVocabulary: readonly VocabularyItem[] = stageVocabularySeeds.flatMap(
  ({ stage, entries }) => entries.map((entry) => createVocabularyItem(stage, entry)),
);
